### ISSUE TITLE
What does squeakr-count count?

### ISSUE THREAD

**Issue by membranepotential** [splatlab/squeakr#20]
Hey,

I tried to understand which kmers are counted by squeakr-count. I noticed that only the first k bases from the input reads are counted, and the kmers further down the reads are discarded. Also sometimes the reverse complement kmer is counted.

Is this within the specifications of squeakr-count?

Cheers!

**Comment by rob-p** [comment]
Hi @membranepotential,

> I noticed that only the first k bases from the input reads are counted, and the kmers further down the reads are discarded.

This _should not happen_, and is not within spec.  If you're seeing this behavior, it is clearly a bug.  Can you provide a test case to reproduce it?

> Also sometimes the reverse complement kmer is counted.

Yes, this is the intended behavior.  Squeakr counts _canonical_ k-mers.  That is, let rc() be the reverse-complement function.  Before hashing a k-mer, Squeaker considers both k and k'=rc(k).  It hashes whichever is lexicographically smaller.  This is generally default behavior of k-mer counters, since often sequencing reads don't have prescribed (absolute) orientation, and when looking at structures like the de Bruijn graph, one almost always wants to associate each k-mer with its reverse-complement.  Allowing one to disable this behavior (via a flag) would not be difficult, if there is a compelling need.

**Comment by membranepotential** [comment]
Hi Rob,

Thanks a lot for your explanation.

I am so sorry, I printed the first round of kmers that are inserted into the CQF, but overlooked the part where it inserts the other kmers. So this indeed works as intended and as I expected.

Also the part about canonical k-mers makes sense. I want to index RNAseq data, which typically should be strand specific nowadays (please correct me if I am wrong here). I will check if using the canonical kmers will give me false positives. It'll probably make more sense to just use longer kmers in that case.

One more question: In the CQF you have keys and values, but the value is always set to 0 right? And you then count the elements in the multi-set of (kmer, 0) tuples?

I noticed that the function `uint64_t qf_count_key(const QF *qf, uint64_t key);` is declared in `gqf.h`, but not implemented yet.

Cheers and thanks again

**Comment by prashantpandey** [comment]
Hi @membranepotential,

Yeah, you are right. We have <key, value> tuples in the CQF and we insert them one at a time and count them as in a multiset. In k-mer counting, the value is always 0 and we don't use any space for it. 

The function `uint64_t qf_count_key(const QF *qf, uint64_t key);` is implemented in a separate CQF code repo but we have integrated it with the Squeakr repo. This function returns the number of times a key has been inserted, with any value, However, given that values are always 0 we don't need this function in Squeakr.

Please let me know if you have a use-case wherein you need this and we can definitely add the implementation.

Thanks,
Prashant

**Comment by membranepotential** [comment]
Hey Prashant,

thanks for the clarification. No use-case, I am just trying to make sense of the code :).

Cheers!
