### ISSUE TITLE
Segmentation fault while counting human genome

### ISSUE THREAD

**Issue by Colelyman** [splatlab/squeakr#33]
I am trying to use `squeakr` to count kmers from the human genome assembly GRCh38. As suggested in #31 I have taken each chromosome and added dummy quality values to convert it into FASTQ. 

I am currently on master [346f581](https://github.com/splatlab/squeakr/commit/346f5818f4e2f3330c9ae305dbbc0f52a62f04c6) and I run the following command

    ./squeaker count -k 20 -t 1 -o ./output human.fq

where `human.fq` is the FASTQ converted file of the human genome assembly. The output that I get is:

    [2019-01-07 11:22:17.136] [squeakr_console] [info] Reading from the fastq file and inserting in the CQF.
    Segmentation fault (core dumped)

Any ideas for what I can do to fix this? Thanks!

**Comment by prashantpandey** [comment]
Hi @Colelyman,

Could you please share a sample input file to reproduce the issue. 

Thanks,
Prashant

**Comment by Colelyman** [comment]
Here is a smaller example file (the first human chromosome, still produces the error), available for download (249 MB) https://drive.google.com/open?id=1Bo0sN89X1Mrnhn1tF5Zmi9CWdIW4ZzH8

Let me know if you have trouble downloading it.

**Comment by Colelyman** [comment]
Any updates on this issue?

Thanks,
Cole

**Comment by rob-p** [comment]
Hi @Colelyman,

  Apologies for the delay in getting around to this.  We know what the cause is here.  The FASTA/Q parsing strategy we use parses the file in "blocks", with the assumption that each block will contain at least one complete record.  Since blocks are large (they can be MB), this is true with sequencing reads (even long reads).  However, when the "reads" are a reference genome, as is the case here, that can cause a problem.  One solution is to make the block size large enough to cover the biggest contig in the assembly (@prashantpandey can point you at the line of code that would need to be changed for that).  A better solution would be to "fix" our parser to avoid this assumption, but we've not had a chance to do that yet.

Best,
Rob

**Comment by prashantpandey** [comment]
Thanks, @rob-p. @Colelyman, you can increase the block size in `reader.h`
```
diff --git a/include/reader.h b/include/reader.h
index 679bf0d..c35669e 100644
--- a/include/reader.h
+++ b/include/reader.h
@@ -99,7 +99,7 @@ bool reader::fastq_read_parts(int mode, file_pointer *fp) {
        reader& file_reader = *(fp->freader.get());
 
        uint32_t OVERHEAD_SIZE = 65535;
-       uint64_t part_size = 1ULL << 25;
+       uint64_t part_size = 1ULL << 29;
        char *part = (char *)malloc((part_size + OVERHEAD_SIZE)*sizeof(char));
        memcpy(part, part_buffer, part_filled);
```
I have tried the code with the above change and it didn't crash. 
We will notify you when we push the new parser changes in the repo. 

Thanks,
Prashant

**Comment by Colelyman** [comment]
@rob-p @prashantpandey thank you so much! I will try this out.

**Comment by t-kranz** [comment]
I'm experiencing the same problem for a genome dataset with commit 695edb8a389f5f80f0622774364d7dca9a09abf5.

I can confirm the suggested change/workaround by prashantpandey is working. 

Please reopen this ticket (so its easier to find) until you get a chance to actually fix the parsing strategy and/or add the information to the projects README.md

Sincerely tkranz
